version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/instance-scheduler"
    schedule:
      interval: "daily"
    groups:
      gomod-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    directory: "/instance-scheduler"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"    
    groups:
      action-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    
