version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/instance-scheduler"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/instance-scheduler"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
