version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "instance-scheduler"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
