AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  modernisation-platform-instance-scheduler

  SAM Template for modernisation-platform-instance-scheduler

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    # This timeout configuration only takes effect when running the lambda locally through SAM
    # (sam local invoke --event event.json). We deploy the lambda through Terraform aws_lambda_function resource,
    # in the main repository (modernisation-platform). Therefore, to configure timeout for the deployed lambda, refer
    # to the relevant timeout property in Terraform.
    # 600 seconds = 10 minutes
    Timeout: 600
    Tracing: Active
  Api:
    TracingEnabled: True

Resources:
  InstanceSchedulerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      ImageUri: instance-scheduler:1.0
      CodeUri: instance-scheduler/
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /instance-scheduler
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          INSTANCE_SCHEDULING_SKIP_ACCOUNTS: oasys-development,apex-development,data-and-insights-wepi-development,xhibit-portal-development,nomis-preproduction,testing-test,oasys-preproduction,tariff-development,mlra-development,nomis-development,example-development,performance-hub-preproduction,xhibit-portal-preproduction,delius-iaps-development,performance-hub-development,ppud-development,refer-monitor-development,digital-prison-reporting-development,oasys-test,equip-development,threat-and-vulnerability-mgmt-development,nomis-test,ccms-ebs-development,maatdb-development,
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./instance-scheduler
      DockerTag: 1.0
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  InstanceSchedulerAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/instance-scheduler/"
  InstanceSchedulerFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt InstanceSchedulerFunction.Arn
  InstanceSchedulerFunctionIamRole:
    Description: "Implicit IAM Role created for Instance Scheduler function"
    Value: !GetAtt InstanceSchedulerFunctionRole.Arn
